### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by kristianmandrup** [bryanrsmith/aurelia-react-loader#1]
I assume this would work just fine with React Native as well?
Would be nice to mention. Thanks :)

**Comment by bryanrsmith** [comment]
I would think not. This uses react-dom to render components into their host DOM elements. I don't know much about RN, but my understanding is that there is no DOM.

**Comment by kristianmandrup** [comment]
Yeah, it's a pity if Aurelia requires there to be a DOM to render to...? Otherwise it would work for sure!
