### ISSUE TITLE
Example react component includes code in jsx format

### ISSUE THREAD

**Issue by palktonderAtpowelno** [bryanrsmith/aurelia-react-loader#3]
Hi, I love the idea behind this plugin, but I have a slight problem. Since the react component includes code in jsx format but has the js extension, the js compilation fails. If I change the extension to jsx the require loading fails. How is this meant to work?

I would really appreciate an answer since I'm presenting Aurelia at a meetup tomorrow and would love to be able to show the React integration at the meetup

**Comment by bryanrsmith** [comment]
It sounds like you need to either adjust your transpiler to process .jsx files (or use a loader plugin that does it, like https://github.com/floatdrop/plugin-jsx), or you need to adjust your loader config to handle the .jsx extension in imports. Or maybe you can explicitly select the loader with something like `script.jsx!javascript`? Need more info about your setup.

**Comment by palktonderAtpowelno** [comment]
I'm actually referring to your example in the README.md. Just to try it out I tried to follow that, but then I ran into the problem with my-react-component.js including the return statement that looks to me as jsx formatted code (I know very little React). 

Also the require statement in the html refers to the js extension. Again, it might be something I've misunderstood here so please help me.

**Comment by palktonderAtpowelno** [comment]
I figured it out using gulp-babel babel-plugin-transform-react-jsx and a lot of fiddling. Maybe some hints in the README.md would make it an easier experience. But it looks really good :-)

**Comment by bryanrsmith** [comment]
Glad to hear it! Sorry I didn't have a chance to get back to you earlier.
