### ISSUE TITLE
PR's accepted?

### ISSUE THREAD

**Issue by fragsalat** [bryanrsmith/aurelia-react-loader#5]
Do you accept PR's and are willing to publish a new version to npm or add me as publisher?
I've improved this since 1 year and got a quite good version which allows even passing children via dom and uses the lifecycle of React / Preact.

**Comment by bryanrsmith** [comment]
Hi @fragsalat! I don't use this project and more & have no plans to maintain it. If you're up for it I'm definitely happy to add you as a contributor here and a publisher on npm. What's your npm username?

**Comment by fragsalat** [comment]
Cool. My npm name is fragsalat as well. I would move this repository to my account and maintain it there if it's ok for you.

**Comment by bryanrsmith** [comment]
I'd rather not transfer the repo, but I've added you as a maintainer both here and on npm.
